version: '3.4'

services:
  mypatientapp:
    image: mypatientapp
    build:
      context: my-patient-app
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
